/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#0064e0',
        'primary-deep': '#0457cb',
        'primary-soft': '#0091ff',
        'on-primary': '#ffffff',
        'ink-button': '#000000',
        'on-ink-button': '#ffffff',
        'fb-blue': '#1876f2',
        'meta-link': '#385898',
        'oculus-purple': '#a121ce',
        'success': '#31a24c',
        'success-bg': '#24e400',
        'attention': '#f2a918',
        'warning': '#f7b928',
        'warning-bg': '#ffe200',
        'critical': '#e41e3f',
        'critical-strong': '#f0284a',
        'canvas': '#ffffff',
        'surface-soft': '#f1f4f7',
        'ink-deep': '#0a1317',
        'ink': '#1c1e21',
        'charcoal': '#444950',
        'slate': '#4b4c4f',
        'steel': '#5d6c7b',
        'stone': '#8595a4',
        'hairline': '#ced0d4',
        'hairline-soft': '#dee3e9',
        'disabled-text': '#bcc0c4',
      },
      fontFamily: {
        sans: ['Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'hero-display': ['64px', { lineHeight: '1.16', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '1.17', fontWeight: '500' }],
        'heading-lg': ['36px', { lineHeight: '1.28', fontWeight: '500' }],
        'heading-md': ['28px', { lineHeight: '1.21', fontWeight: '300' }],
        'heading-sm': ['24px', { lineHeight: '1.25', fontWeight: '500' }],
        'subtitle-lg': ['18px', { lineHeight: '1.44', fontWeight: '700' }],
        'subtitle-md': ['18px', { lineHeight: '1.44', fontWeight: '400' }],
        'body-md-bold': ['16px', { lineHeight: '1.50', fontWeight: '700', letterSpacing: '-0.16px' }],
        'body-md': ['16px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '-0.16px' }],
        'body-sm-bold': ['14px', { lineHeight: '1.43', fontWeight: '700', letterSpacing: '-0.14px' }],
        'body-sm': ['14px', { lineHeight: '1.43', fontWeight: '400', letterSpacing: '-0.14px' }],
        'caption-bold': ['12px', { lineHeight: '1.33', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '1.33', fontWeight: '400' }],
        'button-md': ['14px', { lineHeight: '1.43', fontWeight: '700', letterSpacing: '-0.14px' }],
        'link-md': ['16px', { lineHeight: '1.50', fontWeight: '700', letterSpacing: '-0.16px' }],
      },
      borderRadius: {
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '16px',
        'xxl': '24px',
        'xxxl': '32px',
        'feature': '40px',
        'full': '100px',
        'circle': '9999px',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '10px',
        'md': '12px',
        'base': '16px',
        'lg': '20px',
        'xl': '24px',
        'xxl': '32px',
        'xxxl': '40px',
        'section-sm': '48px',
        'section': '64px',
        'section-lg': '80px',
        'hero': '120px',
      },
      boxShadow: {
        'sticky-panel': 'rgba(20, 22, 26, 0.3) 0px 1px 4px 0px',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        'fade-in': 'fadeIn 0.8s ease-out forwards',
        'blob': 'blob 7s infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        float: {
          '0%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
          '100%': { transform: 'translateY(0px)' },
        }
      }
    },
  },
  plugins: [],
}
